### ISSUE TITLE
Is there a way to get CommonJS export behavior back?

### ISSUE THREAD

**Issue by jperl** [Kflash/trolly#10]
````
/**
* Migrating from Babel >= 5.x to Babel >= 6.x, will most likely break your code
* because Babel now have killed the CommonJS default export behaviour.
*
As a workaround, replace export default { … } with module.exports = { … }
*/
````

Is there a way to fix this?

**Comment by Kflash** [comment]
Hi. Huge design changes have been done with Babel 6.x. And Babel 5.x is now deprecated and no longer maintained. So all I can say is: this is the future. 

However. Internally you can still use the import export default, but in the main file where you want to expose the whole library, you should be using `module.exports = { … }`.

Else everything get wrapped inside default.

If you still prefer the 5.x solution, you have to add `.default` behind the exported file. Example:

```js
 // library
const foo = function() {  return 'Hello, World!'; };
export default foo.
```

Then you can do
const foo = require('foo').default

But that will give you issues with browsers, and a hell lot of extra code to write.

So the prefered solution would be to get the same result as in Babel 5.x

```js
 // library
const foo = function() {  return 'Hello, World!'; };
module.exports = foo;
```
Then you can do

`const foo = require('foo').default`

or

`import foo from './foo'`

**Comment by jperl** [comment]
Thank you, this is tremendously helpful!

**Comment by jperl** [comment]
I am using trolly as the skeleton for https://github.com/DispatchMe/datafactory. You saved me a few days of hassle trying to figure out how to get all of these things working together. Thank you!

**Comment by Kflash** [comment]
Hi. Glad you liked it :+1: I tried to put together something that everything could use. 

You may need to adjust the workflow after your own needs. Have a look here: https://github.com/Kflash/trolly#there-seems-to-be-some-configuration-settings-that-is-not-used-why

Only thing you can't switch off is the notification that pops up when you build the library, and succeed.

If you run into a dark corner with trolly, feel free to drop me an email. You find the adr on my profile.
