### ISSUE TITLE
webpack config path are not correct

### ISSUE THREAD

**Issue by lostdalek** [Kflash/trolly#13]
I've found two other issues when launching the webpack dev server:
entry: the library source is missing
paths used by webpack are not good (_root variable fault)

PR incoming :)

**Comment by Kflash** [comment]
Thanks again! I know there is a known issue with the coverage report too. I think it's a path issue. Any ideas?

**Comment by lostdalek** [comment]
you're welcome! you have created a great generic boilerplate, thank you :)

i'll check if i find something for the coverage report issue

**Comment by Kflash** [comment]
I just updated the dependencies so PhantomJS 2.x are now supported.
