### ISSUE TITLE
add a github bot

### ISSUE THREAD

**Issue by Kflash** [Kflash/trolly#24]
@brucek Any idea how to add a github bot ala what you find in the Angular, React, jquery repo etc.

Plan to add it.

**Comment by Kflash** [comment]
close this for now

**Comment by brucek** [comment]
Not sure what you mean :-?

**Comment by Kflash** [comment]
In this thread you see a bot

https://github.com/angular/angular.js/pull/14297

**Comment by Kflash** [comment]
Other examples

- @googlebotgooglebot added the cla: yes label 23 hours ago

They do different tasks

**Comment by Kflash** [comment]
More bot examples

https://github.com/facebook/react/pull/5811

**Comment by brucek** [comment]
sorry, no idea on this one :-/
